@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR


package "Command classes"{
Class "{abstract}\nCommand" as Command
Class AddCommand
Class DeleteCommand
Class ExitCommand
Class ListCommand
Class LoadFromStorageCommand
Class MyListCommand
Class SaveToStorageCommand
Class ViewCommand
}


package Storage{
Class Storage
}



Class HiddenModel #FFFFFF

HiddenModel ..> Command


AddCommand -up-|> Command
DeleteCommand -up-|> Command
ExitCommand -up-|> Command
ListCommand -up-|> Command
MyListCommand -up-|> Command
LoadFromStorageCommand -up-|> Command
SaveToStorageCommand -up-|> Command
ViewCommand -up-|> Command

SaveToStorageCommand ..> Storage
LoadFromStorageCommand ..> Storage


@enduml