@startuml
'https://plantuml.com/object-diagram

object Duke
object Ui
object TaskList
object Storage
object Event
object ToDo
object Deadline

Ui - Duke
Duke "1" --> "1" TaskList : Has
Duke - Storage
TaskList --> "0..*" Event : Contains
TaskList --> "0..*" ToDo : Contains
TaskList --> "0..*" Deadline : Contains



@enduml
